### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by gitduk** [Murzchnvok/ugly-todo#3]
❯ utd
Traceback (most recent call last):
  File "/home/wukaige/.local/bin/utd", line 4, in <module>
    from cli.app import show
  File "/home/wukaige/.opt/ugly-todo/src/cli/app.py", line 5, in <module>
    from util import notify
  File "/home/wukaige/.opt/ugly-todo/src/util.py", line 4, in <module>
    PaddingSize = tuple[int, int] | tuple[int, int, int, int]
TypeError: 'type' object is not subscriptable

❯ python --version
Python 3.8.10

❯ pip list | grep rich
rich                          11.2.0

why?

**Comment by Murzchnvok** [comment]
This happened because of the way I wrote the type hints, it's only supported by python3.10+ if I'm not mistaken. I'd suggest you to update your python version to the latest version, that should solve the problem.

**Comment by gitduk** [comment]
@Murzchnvok 

❯ python --version
Python 3.10.0
❯ utd
Traceback (most recent call last):
  File "/home/wukaige/.local/bin/utd", line 4, in <module>
    from cli.app import show
  File "/home/wukaige/.opt/ugly-todo/src/cli/app.py", line 5, in <module>
    from util import notify
  File "/home/wukaige/.opt/ugly-todo/src/util.py", line 4, in <module>
    PaddingSize = tuple[int, int] | tuple[int, int, int, int]
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'

**Comment by gitduk** [comment]
@Murzchnvok 
❯ python --version
Python 3.10.2
❯ utd
Traceback (most recent call last):
  File "/home/wukaige/.local/bin/utd", line 4, in <module>
    from cli.app import show
  File "/home/wukaige/.opt/ugly-todo/src/cli/app.py", line 5, in <module>
    from util import notify
  File "/home/wukaige/.opt/ugly-todo/src/util.py", line 4, in <module>
    PaddingSize = tuple[int, int] | tuple[int, int, int, int]
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'

what happened？

**Comment by Murzchnvok** [comment]
Not sure, unfortunately I don't know how to reproduce the same problem.
